### ISSUE TITLE
Beta feedback

### ISSUE THREAD

**Issue by zeke** [voltraco/docs#1]
Just got my invitation! A few impressions:

red on black is hard to read

<img width="354" alt="screen shot 2016-08-24 at 9 53 34 pm" src="https://cloud.githubusercontent.com/assets/2289/17957350/e150167a-6a45-11e6-92c4-115d44cc4be5.png">

The password requirement is too rigid. I generated several 16-character passwords with 1password that included numbers, letters, mixed case, and special characters, but all were rejected because they didn't include the "right" special characters.

the three-step indicator thingy overlapped with the button at some point:

<img width="235" alt="screen shot 2016-08-24 at 9 54 45 pm" src="https://cloud.githubusercontent.com/assets/2289/17957407/47650d6c-6a46-11e6-852d-2e246fea3212.png">

On import of my ~100GB library, the app froze and I had to force quit:

<img width="162" alt="screen shot 2016-08-24 at 10 02 38 pm" src="https://cloud.githubusercontent.com/assets/2289/17957461/b79cec3a-6a46-11e6-92f6-d1105a4edbb8.png">

The artists filter is misaligned:

<img width="323" alt="screen shot 2016-08-24 at 10 03 49 pm" src="https://cloud.githubusercontent.com/assets/2289/17957470/cce306ec-6a46-11e6-955d-0d7ccd228882.png">

Loving what I see so far! The live-updating counts on import are my favorite detail yet:

<img width="660" alt="screen shot 2016-08-24 at 9 56 24 pm" src="https://cloud.githubusercontent.com/assets/2289/17957521/3cdb919e-6a47-11e6-9ceb-67de81bebf60.png">

**Comment by aprile** [comment]
Most of these issues have been fixed, thanks for the feedback! 

As for the freeze on import, we would have to dive in a little more to the specific circumstances because we haven't been able to reproduce. @zeke

Also we've opened a public repo for Beta issues here: https://github.com/voltraco/beta/issues

**Comment by zeke** [comment]
Thanks, @aprileelcich! Gonna give Voltra another go.
