### ISSUE TITLE
Create Account Button unresponsive?

### ISSUE THREAD

**Issue by wyatt-e** [voltraco/docs#4]
When signing up for an account, I clicked to read the Terms & Conditions. Though all entry fields seemed to have validated, the Create Account button was darkened and I could not go further. After quitting, restarting, then entering the same information into the three fields, I was able to create an account. The app now skips that screen so I am unable to replicate the issue. OS Sierra 10.12.5

**Comment by aprile** [comment]
@wyatt-e We are currently looking into this problem and trying to reproduce. Thanks for the heads up!
